// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using UIKit;
using MvvmCross.Platforms.Ios.Binding.Views;
using MvvmCross.Binding.BindingContext;
using RecipesBook.Core.DataModel;

namespace RecipesBook.iOS
{
    public partial class CollectionViewCell : MvxCollectionViewCell
	{
		public CollectionViewCell (IntPtr handle) : base (handle)
		{
            
		}

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();



            this.DelayBind(() =>
            {
                var bset = this.CreateBindingSet<CollectionViewCell, Recipe>();
                bset.Bind(titleLabel).To(vm => vm.Name);
                bset.Bind(imageView).For(im => im.ImagePath).To(vm => vm.ImageUrl);
                bset.Apply();
            });
        }
    }
}
