// This file has been autogenerated from a class added in the UI designer.

using System;
using MvvmCross.Platforms.Ios.Views;
using Foundation;
using UIKit;
using RecipesBook.Core.ViewModel;
using MvvmCross.Platforms.Ios.Presenters.Attributes;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Platforms.Ios.Binding.Views;

namespace RecipesBook.iOS
{
    [MvxFromStoryboard("Main")]
    [MvxRootPresentation(WrapInNavigationController = true)]
    public partial class HomeView : MvxViewController<HomeViewModel>
	{
        public HomeView()
        {
        }
        public MvxCollectionViewSource collectionViewSource;

        public HomeView (IntPtr handle) : base (handle)
		{
            
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            Title = "Recipes";
           
            collectionViewSource = new MvxCollectionViewSource(collectionView, new NSString("CollectionViewCell"));
            collectionView.Source = collectionViewSource;

            var set = this.CreateBindingSet<HomeView, HomeViewModel>();
            set.Bind(collectionViewSource).To(vm => vm.Recipes);
            set.Bind(collectionViewSource).For(src=>src.SelectionChangedCommand).To(vm => vm.ShowRecipeDetailCommand);
            set.Apply();
        }
    }
}
