// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Platforms.Ios.Views;
using RecipesBook.Core.ViewModel;
using UIKit;

namespace RecipesBook.iOS
{
    [MvxFromStoryboard("Main")]
    public partial class RecipeDetailsView : MvxViewController<RecipeDetailViewModel>
	{
		public RecipeDetailsView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            scrollView.SetContentOffset(new CoreGraphics.CGPoint(0, this.scrollView.ContentOffset.Y),true);
            scrollView.DirectionalLockEnabled = true;

            Title = ViewModel.Name;
           
            var bset = this.CreateBindingSet<RecipeDetailsView, RecipeDetailViewModel>();
            bset.Bind(difficultyLabel).To(vm => vm.Difficulty);
            bset.Bind(imageRecipe).For(im => im.ImagePath).To(vm => vm.ImageUrl);
            bset.Bind(durationLabel).To(vm => vm.Duration);
            bset.Bind(durationLabel).To(vm => vm.Duration);
            bset.Bind(methodLabel).To(vm => vm.Method);
            bset.Bind(ingredientsList).To(vm => vm.IngredientsText);
            bset.Apply();
        }
    }
}
